/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fr.parisnanterre.rahimadjedomolebarry.backendjava;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication

public class App { // App : la classe de notre application
    public static void main(String[] args) {
        SpringApplication.run(App.class, args);
    
    }
}
