/*
 * This Java source file was generated by the Gradle 'init' task.
 */
/*package fr.parisnanterre.rahimadjedomolebarry.backendjava;


//import javax.security.auth.login.AppConfigurationEntry;

//import static org.junit.Assert.assertNotNull;

import org.junit.Test;
import org.springframework.boot.test.context.SprinBootTest;
import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;

@SpringBootTest // pour que Spring puisse commprendre qu'il doit tester la classe
public class AppTest {
    @Test public void checkApiRun() {
    //assertDoesNotThrow(() -> App.main(new String{}));
    assertDoesNotThrow(() -> App.main(new String[0]));

    }
}*/

        
        // à supprimer
        //@Test public void appHasAGreeting() {
        //App classUnderTest = new App();
        //assertNotNull("app should have a greeting", classUnderTest.getGreeting());


        package fr.parisnanterre.rahimadjedomolebarry.backendjava;

        import org.junit.jupiter.api.Test; // Utilise JUnit 5
        import org.springframework.boot.test.context.SpringBootTest;
        import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;
        
        @SpringBootTest // Indique à Spring Boot d'exécuter le test avec le contexte approprié
        public class AppTest {
        
            @Test
            public void checkApiRun() {
                assertDoesNotThrow(() -> App.main(new String[0])); // Test que l'application démarre sans exception
            }
        }
              
