name: Build

on:                   #quel moment on va déclencher l'action
  push:             #cela veut dire qu'on push dans la branche main et develop
    branches:
      - main
      - develop
  pull_request:    # validation des modifications fait par un tiers et non directement dans le projet
    branches:
      - main


# création du job : ce qui va être lancé
jobs:
  build:

    runs-on: ubuntu-latest    #lancer sur la derniere version d'unbutu
    permissions:
      contents: read

    # Get source code and config java
    steps:                              #configuration pour utiliser java
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'                      #changer la version si nécéssaire
          distribution: 'temurin'

      # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
      # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0  // optimisation

      # Build project
      - name: Build with Gradle Wrapper
        run: ./gradlew build

